
name: Build-docker-image-fw

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-18.04

    steps:

    - uses: actions/checkout@v3
    - name: Branch name
      env:
        BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        GITHUB_REPOSITORY: ${{ GITHUB_REPOSITORY }}
      run: echo running on branch ${BRANCH_NAME}
    - name: Build the Docker image
      run: docker build --build-arg FW_REPO_URL=https://github.com/${GITHUB_REPOSITORY}.git --build-arg FW_BRANCH=${BRANCH_NAME} . --file Dockerfile --tag fw-bench:$(date +%s)
